<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>SharpMonEngine</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharpMonEngine.Battle.Core\SharpMonEngine.Battle.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Builder\" />
    </ItemGroup>

</Project>
